drop table if exists product;
drop table if exists deliveries;

create table products
(
    id    BIGINT generated by default as identity primary key,
    name  varchar(255) not null,
    price double precision
);

create table deliveries
(
    id    BIGINT generated by default as identity primary key,
    product_id  BIGINT not null,
    address varchar(255) not null,

    constraint fk_delivery_product
        foreign key (product_id)
        references products(id)
        on delete cascade
);